In [1]:
import kagglehub
import pandas as pd
import numpy as np
import os
import warnings

# Supresión de warnings
warnings.filterwarnings('ignore')
pd.options.mode.chained_assignment = None

# Configuración de visualización del DataFrame
pd.set_option('display.max_columns', None)   # muestra todas las columnas
pd.set_option('display.max_rows', 100)
pd.set_option('display.float_format', '{:.2f}'.format)

In [2]:

# ── Configuración ──────────────────────────────────────────
DATA_PATH = r"data/raw/inglaterra_argentina_wc_26_raw.csv"  
SEPARATOR = ','               
ENCODING  = "utf-8"             
# ───────────────────────────────────────────────────────────

df_raw = pd.read_csv(DATA_PATH, sep=SEPARATOR, encoding=ENCODING, header=1) # header=1 asigna a la fila 2 como header 
print(f"✅ Dataset cargado — Filas: {df_raw.shape[0]} | Columnas: {df_raw.shape[1]}")

✅ Dataset cargado — Filas: 31 | Columnas: 20

In [3]:
# Ver estado actual de nulos
nulos = pd.DataFrame({
    'Nulos': df_raw.isnull().sum(),
    'Porcentaje': (df_raw.isnull().sum() / len(df_raw) * 100).round(2),
    'Tipo': df_raw.dtypes
})
display(nulos[nulos['Nulos'] > 0].sort_values('Porcentaje', ascending=False))

Empty DataFrame
Columns: [Nulos, Porcentaje, Tipo]
Index: []

In [4]:
# ─── Primeras y últimas filas ──────────────────────────────────────────────
print('\n--- Primeras 5 filas ---')
display(df_raw.head())

print('\n--- Últimas 5 filas ---')
display(df_raw.tail())

# ─── Dimensiones ───────────────────────────────────────────────────────────
print(f'Filas: {df_raw.shape[0]} | Columnas: {df_raw.shape[1]}')

# ─── Tipos de datos ────────────────────────────────────────────────────────
print('\n--- Info general ---')
df_raw.info()

# ─── Valores nulos por columna ─────────────────────────────────────────────
print('\n--- Nulos por columna ---')
# Verificamos si hay algún nulo en toda la tabla
if df_raw.isnull().sum().sum() == 0:
    print('✅ Sin valores nulos')
else:
    # Sino mostramos tabla filtrada de nulos
    nulos = pd.DataFrame({
        'Nulos': df_raw.isnull().sum(),
        'Porcentaje': (df_raw.isnull().sum() / len(df_raw) * 100).round(2)
    })
    display(nulos[nulos['Nulos'] > 0])

# ─── Duplicados ────────────────────────────────────────────────────────────
print(f'\nFilas duplicadas: {df_raw.duplicated().sum()}')

# ─── Estadísticas descriptivas ─────────────────────────────────────────────
print('\n--- Estadísticas descriptivas ---')
display(df_raw.describe())

--- Primeras 5 filas ---

,Harry Kane,9,FW,32,90,0,0.1,0.2,0.3,1,0.4,0.5,0.6,0.7,1.1,0.8,1.2,0.9,0.10,0.11
0,Anthony Gordon,18,AM,25,71,1,0,0,0,1,1,0,0,1,1,0,2,0,0,0
1,Ezri Konsa,2,"DF,FW",28,19,0,0,0,0,0,0,0,0,0,0,0,2,0,1,0
2,Jude Bellingham,10,AM,23,90,0,0,0,0,0,0,0,0,3,4,0,0,1,1,0
3,Morgan Rogers,17,AM,23,90,0,1,0,0,1,0,0,0,2,1,1,4,0,0,0
4,Elliot Anderson,8,DM,23,90,0,0,0,0,0,0,1,0,2,4,0,0,2,1,0

--- Últimas 5 filas ---

,Harry Kane,9,FW,32,90,0,0.1,0.2,0.3,1,0.4,0.5,0.6,0.7,1.1,0.8,1.2,0.9,0.10,0.11
26,Nicolás Otamendi,19,DF,38,19,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
27,Cristian Romero,13,CB,28,90,0,0,0,0,0,0,1,0,2,1,0,0,3,2,0
28,Nahuel Molina,26,RB,28,71,0,0,0,0,0,0,0,0,1,0,0,1,0,1,0
29,Gonzalo Montiel,4,DF,29,19,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0
30,Emiliano Martínez,23,GK,33,90,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0

Filas: 31 | Columnas: 20

--- Info general ---
<class 'pandas.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 20 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Harry Kane  31 non-null     str
 1   9           31 non-null     int64
 2   FW          31 non-null     str
 3   32          31 non-null     int64
 4   90          31 non-null     int64
 5   0           31 non-null     int64
 6   0.1         31 non-null     int64
 7   0.2         31 non-null     int64
 8   0.3         31 non-null     int64
 9   1           31 non-null     int64
 10  0.4         31 non-null     int64
 11  0.5         31 non-null     int64
 12  0.6         31 non-null     int64
 13  0.7         31 non-null     int64
 14  1.1         31 non-null     int64
 15  0.8         31 non-null     int64
 16  1.2         31 non-null     int64
 17  0.9         31 non-null     int64
 18  0.10        31 non-null     int64
 19  0.11        31 non-null     int64
dtypes: int64(18), str(2)
memory usage: 5.0 KB

--- Nulos por columna ---
✅ Sin valores nulos

Filas duplicadas: 0

--- Estadísticas descriptivas ---

,9,32,90,0,0.1,0.2,0.3,1,0.4,0.5,0.6,0.7,1.1,0.8,1.2,0.9,0.10,0.11
count,31.00,31.00,31.00,31.00,31.00,31.00,31.00,31.00,31.00,31.00,31.00,31.00,31.00,31.00,31.00,31.00,31.00,31.00
mean,12.71,28.39,60.97,0.10,0.10,0.00,0.00,0.61,0.23,0.13,0.00,0.84,0.81,0.13,1.06,0.58,0.48,0.00
std,7.99,4.33,34.62,0.30,0.40,0.00,0.00,1.02,0.43,0.34,0.00,1.21,1.11,0.34,1.79,0.99,0.68,0.00
min,1.00,21.00,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
25%,5.50,25.50,19.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
50%,11.00,28.00,80.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,1.00,0.00,0.00,0.00,0.00,0.00
75%,19.50,32.00,90.00,0.00,0.00,0.00,0.00,1.00,0.00,0.00,0.00,1.00,1.00,0.00,2.00,1.00,1.00,0.00
max,26.00,39.00,90.00,1.00,2.00,0.00,0.00,4.00,1.00,1.00,0.00,5.00,4.00,1.00,9.00,4.00,2.00,0.00

In [5]:
# ── Eliminar columna entera ────────────────────────────────────────────────
# Cuándo: más del 50% de nulos y la columna no aporta valor
df_raw = df_raw.drop(columns=['PKwon', 'PKcon'])        # ← reemplazar

KeyError: "['PKwon', 'PKcon'] not found in axis"

In [6]:
# Opción A — quedarse solo con los años (más simple)
df_raw['Age'] = df_raw['Age'].str.split('-').str[0].astype(int)

KeyError: 'Age'

In [ ]:
# Ver si el índice tiene huecos
print(f'Índice antes del reset: {df_raw.index.tolist()[:10]}...')

# Resetear
df_raw = df_raw.reset_index(drop=True)

# Verificar
print(f'Índice después del reset: {df_raw.index.tolist()[:10]}...')
print(f'Filas finales: {df_raw.shape[0]}')

In [ ]:
print('=' * 50)
print('REPORTE FINAL DE CALIDAD')
print('=' * 50)
print(f'Filas finales:      {df_raw.shape[0]}')
print(f'Columnas:           {df_raw.shape[1]}')
print(f'Duplicados:         {df_raw.duplicated().sum()}')
print(f'Nulos totales:      {df_raw.isnull().sum().sum()}')
print('=' * 50)

In [ ]:
# Tipos de datos finales
print(df_raw.dtypes)

In [ ]:
df_raw

In [ ]:
# Renombrar a df_clean antes de exportar
df_clean = df_raw.copy()

# Exportar
nombre_salida = "data/clean/inglaterra_argentina_wc_26_clean.csv"    
df_clean.to_csv(nombre_salida, index=False, encoding='utf-8')
print(f'Dataset exportado: {nombre_salida}')
print(f'Filas: {df_clean.shape[0]} | Columnas: {df_clean.shape[1]}')