<a href="https://colab.research.google.com/github/andressonsino/football-data-analysis/blob/main/huracan/notebooks/san_lorenzo_huracan.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import seaborn as sns
import warnings

# Supresión de warnings
warnings.filterwarnings('ignore')
pd.options.mode.chained_assignment = None

# Configuración de visualización del DataFrame
pd.set_option('display.max_columns', None)   # muestra todas las columnas
pd.set_option('display.max_rows', 100)
pd.set_option('display.float_format', '{:.2f}'.format)

# Configuración de gráficos
sns.set_theme(style='whitegrid')
sns.set_palette('husl')
plt.rcParams['figure.figsize'] = (12, 6)
plt.rcParams['axes.titlesize'] = 16
plt.rcParams['axes.labelsize'] = 13

In [6]:

# ── Configuración ──────────────────────────────────────────
# DATA_PATH = r"../data/raw/san_lorenzo_huracan_raw.csv" # para jupyter
DATA_PATH = r"/san_lorenzo_huracan_raw.csv"   # para colab
SEPARATOR = ","
ENCODING  = "utf-8"
# ───────────────────────────────────────────────────────────

df_raw = pd.read_csv(DATA_PATH, sep=SEPARATOR, encoding=ENCODING)
print(f"✅ Dataset cargado — Filas: {df_raw.shape[0]} | Columnas: {df_raw.shape[1]}")

✅ Dataset cargado — Filas: 29 | Columnas: 24

# LIMPIEZA

In [7]:
# ─── Primeras y últimas filas ──────────────────────────────────────────────
print('\n--- Primeras 5 filas ---')
display(df_raw.head())

print('\n--- Últimas 5 filas ---')
display(df_raw.tail())

# ─── Dimensiones ───────────────────────────────────────────────────────────
print(f'Filas: {df_raw.shape[0]} | Columnas: {df_raw.shape[1]}')

# ─── Tipos de datos ────────────────────────────────────────────────────────
print('\n--- Info general ---')
df_raw.info()

# ─── Valores nulos por columna ─────────────────────────────────────────────
print('\n--- Nulos por columna ---')
# Verificamos si hay algún nulo en toda la tabla
if df_raw.isnull().sum().sum() == 0:
    print('✅ Sin valores nulos')
else:
    # Sino mostramos tabla filtrada de nulos
    nulos = pd.DataFrame({
        'Nulos': df_raw.isnull().sum(),
        'Porcentaje': (df_raw.isnull().sum() / len(df_raw) * 100).round(2)
    })
    display(nulos[nulos['Nulos'] > 0])

# ─── Duplicados ────────────────────────────────────────────────────────────
print(f'\nFilas duplicadas: {df_raw.duplicated().sum()}')

# ─── Estadísticas descriptivas ─────────────────────────────────────────────
print('\n--- Estadísticas descriptivas ---')
display(df_raw.describe())

--- Primeras 5 filas ---

,Player,#,Nation,Pos,Age,Min,Gls,Ast,PK,PKatt,Sh,SoT,CrdY,CrdR,Fls,Fld,Off,Crs,TklW,Int,OG,PKwon,PKcon,-9999
0,Rodrigo Auzmendi,29,ar ARG,FW,25-219,90,0,0,0,0,5,1,1,0,2,2,2,0,0,0,0,NaN,NaN,c89d0b23
1,Alexis Cuello,9,ar ARG,FW,26-172,90,0,0,0,0,1,0,0,0,1,3,0,2,1,0,0,NaN,NaN,0bf6b89a
2,Nicolás Tripichio,24,ar ARG,CM,30-216,90,0,0,0,0,1,0,0,0,3,2,0,1,1,2,0,NaN,NaN,4c3e3d0a
3,Martín Río,27,ar ARG,CM,25-148,52,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,NaN,NaN,5b3a9431
4,Juan Rattalino,13,ar ARG,MF,22-198,38,0,0,0,0,0,0,0,0,0,1,0,3,0,0,0,NaN,NaN,98dc6e33

--- Últimas 5 filas ---

,Player,#,Nation,Pos,Age,Min,Gls,Ast,PK,PKatt,Sh,SoT,CrdY,CrdR,Fls,Fld,Off,Crs,TklW,Int,OG,PKwon,PKcon,-9999
24,Máximo Palazzo,35,ar ARG,LB,21-064,90,0,0,0,0,0,0,0,0,3,0,0,4,3,0,0,NaN,NaN,90b5bc97
25,Lucas Carrizo,3,ar ARG,CB,29-081,90,0,0,0,0,0,0,1,0,2,2,0,0,2,0,0,NaN,NaN,2bfc68c3
26,Hugo Nervo,21,ar ARG,CB,35-215,90,0,0,0,0,0,0,0,0,0,0,0,0,3,0,0,NaN,NaN,6afd25e6
27,Lucas Blondel,2,ch SUI,RB,29-329,90,0,0,0,0,3,1,0,0,2,1,0,1,0,1,0,NaN,NaN,4b97076c
28,Hernán Galíndez,1,ec ECU,GK,39-132,90,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,89c136f6

Filas: 29 | Columnas: 24

--- Info general ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29 entries, 0 to 28
Data columns (total 24 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Player  29 non-null     object
 1   #       29 non-null     int64
 2   Nation  29 non-null     object
 3   Pos     29 non-null     object
 4   Age     29 non-null     object
 5   Min     29 non-null     int64
 6   Gls     29 non-null     int64
 7   Ast     29 non-null     int64
 8   PK      29 non-null     int64
 9   PKatt   29 non-null     int64
 10  Sh      29 non-null     int64
 11  SoT     29 non-null     int64
 12  CrdY    29 non-null     int64
 13  CrdR    29 non-null     int64
 14  Fls     29 non-null     int64
 15  Fld     29 non-null     int64
 16  Off     29 non-null     int64
 17  Crs     29 non-null     int64
 18  TklW    29 non-null     int64
 19  Int     29 non-null     int64
 20  OG      29 non-null     int64
 21  PKwon   0 non-null      float64
 22  PKcon   0 non-null      float64
 23  -9999   29 non-null     object
dtypes: float64(2), int64(17), object(5)
memory usage: 5.6+ KB

--- Nulos por columna ---

       Nulos  Porcentaje
PKwon     29      100.00
PKcon     29      100.00

Filas duplicadas: 0

--- Estadísticas descriptivas ---

,#,Min,Gls,Ast,PK,PKatt,Sh,SoT,CrdY,CrdR,Fls,Fld,Off,Crs,TklW,Int,OG,PKwon,PKcon
count,29.00,29.00,29.00,29.00,29.00,29.00,29.00,29.00,29.00,29.00,29.00,29.00,29.00,29.00,29.00,29.00,29.00,0.00,0.00
mean,17.07,67.28,0.07,0.03,0.00,0.00,0.76,0.24,0.21,0.03,1.07,1.07,0.10,1.28,1.24,0.59,0.00,NaN,NaN
std,13.20,27.85,0.37,0.19,0.00,0.00,1.55,0.58,0.41,0.19,1.25,1.22,0.41,1.85,1.15,1.30,0.00,NaN,NaN
min,1.00,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN
25%,7.00,45.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN
50%,13.00,89.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,1.00,1.00,0.00,1.00,1.00,0.00,0.00,NaN,NaN
75%,24.00,90.00,0.00,0.00,0.00,0.00,1.00,0.00,0.00,0.00,2.00,2.00,0.00,1.00,2.00,0.00,0.00,NaN,NaN
max,54.00,90.00,2.00,1.00,0.00,0.00,6.00,2.00,1.00,1.00,5.00,4.00,2.00,7.00,4.00,5.00,0.00,NaN,NaN

In [8]:
#── Eliminar columna entera ────────────────────────────────────────────────
# Cuándo: más del 50% de nulos y la columna no aporta valor
df_raw = df_raw.drop(columns=['PKwon', 'PKcon', '-9999'])

In [9]:
# Nos quedamos solo con los últimos 3 caracteres de cada fila en la columna 'Nation'
df_raw['Nation'] = df_raw['Nation'].str[-3:]

In [10]:
df_raw

,Player,#,Nation,Pos,Age,Min,Gls,Ast,PK,PKatt,Sh,SoT,CrdY,CrdR,Fls,Fld,Off,Crs,TklW,Int,OG
0,Rodrigo Auzmendi,29,ARG,FW,25-219,90,0,0,0,0,5,1,1,0,2,2,2,0,0,0,0
1,Alexis Cuello,9,ARG,FW,26-172,90,0,0,0,0,1,0,0,0,1,3,0,2,1,0,0
2,Nicolás Tripichio,24,ARG,CM,30-216,90,0,0,0,0,1,0,0,0,3,2,0,1,1,2,0
3,Martín Río,27,ARG,CM,25-148,52,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0
4,Juan Rattalino,13,ARG,MF,22-198,38,0,0,0,0,0,0,0,0,0,1,0,3,0,0,0
5,Facundo Gulli,10,ARG,CM,20-318,52,0,0,0,0,0,0,0,0,0,3,0,4,1,0,0
6,Gustavo Del Prete,21,ARG,FWMF,30-058,38,0,0,0,0,0,0,0,0,0,4,0,1,1,0,0
7,Mathías De Ritis,6,URU,LB,23-190,45,0,0,0,0,0,0,1,0,1,2,0,1,2,1,0
8,Teo Rodríguez,3,ARG,DF,20-301,45,0,0,0,0,1,1,0,0,1,0,0,6,1,0,0
9,Alejo Córdoba,35,ARG,CB,22-094,90,0,0,0,0,0,0,0,0,0,1,0,1,3,5,0
10,Danilo Arboleda,2,COL,CB,31-085,90,0,0,0,0,0,0,0,0,0,1,1,0,1,4,0
11,Emiliano Amor,19,SYR,CB,31-085,90,0,0,0,0,0,0,0,0,0,0,0,0,2,3,0
12,Nicolás Blanco,54,ARG,RB,19-121,62,0,0,0,0,0,0,0,0,1,1,0,2,1,1,0
13,José Devecchi,25,ARG,GK,31-031,28,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
14,Orlando Gill,12,PAR,GK,26-059,61,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0
15,Oscar Cortés,7,COL,FW,22-249,89,0,0,0,0,1,0,0,0,2,1,0,0,1,0,0
16,Óscar Romero,10,PAR,FWMF,34-036,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
17,Jordy Caicedo,9,ECU,FW,28-264,65,2,0,0,0,3,2,1,0,1,0,0,1,1,0,0
18,Ignacio Pussetto,23,ARG,FWMF,30-231,25,0,0,0,0,0,0,1,0,1,1,0,1,2,0,0
19,Juan Bisanz,17,ARG,FW,24-346,90,0,0,0,0,6,2,0,0,0,0,0,1,1,0,0
20,Leonardo Gil,8,ARG,CM,35-070,90,0,0,0,0,0,0,0,0,1,0,0,7,2,0,0
21,Rodrigo Fernández,5,URU,CM,30-218,90,0,0,0,0,0,0,0,0,3,1,0,1,3,0,0
22,Facundo Kalinger di Napoli,24,ARG,CM,21-191,77,0,1,0,0,1,0,0,0,5,4,0,0,4,0,0
23,Lautaro Mora,41,ARG,FW,20-165,13,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
24,Máximo Palazzo,35,ARG,LB,21-064,90,0,0,0,0,0,0,0,0,3,0,0,4,3,0,0
25,Lucas Carrizo,3,ARG,CB,29-081,90,0,0,0,0,0,0,1,0,2,2,0,0,2,0,0
26,Hugo Nervo,21,ARG,CB,35-215,90,0,0,0,0,0,0,0,0,0,0,0,0,3,0,0
27,Lucas Blondel,2,SUI,RB,29-329,90,0,0,0,0,3,1,0,0,2,1,0,1,0,1,0
28,Hernán Galíndez,1,ECU,GK,39-132,90,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [11]:
# --- Separar en dos columnas usando regex con grupos -----------------------

# df_raw['edad_anios'] = df_raw['Age'].str.extract(r'^(\d+)')          # Extrae los números antes del guion
# df_raw['edad_dias'] = df_raw['Age'].str.extract(r'-(\d+)').astype(float)  # Extrae los números después del guion

# ── Verificar ────────────────────────────────────────────────────────────
# print(f"NaN en edad_años: {df_raw['edad_anios'].isnull().sum()}")
# print(f"NaN en edad_dias: {df_raw['edad_dias'].isnull().sum()}")
# display(df_raw[['edad_anios', 'edad_dias']].head(5))
#
# ── Eliminar columna original una vez verificado ─────────────────────────
# df_raw = df_raw.drop(columns=['Age'])

NaN en edad_años: 0
NaN en edad_dias: 0

  edad_anios  edad_dias
0         25     219.00
1         26     172.00
2         30     216.00
3         25     148.00
4         22     198.00

In [12]:
# Detectar con IQR
def detectar_outliers(df, columna):
    Q1 = df[columna].quantile(0.25)
    Q3 = df[columna].quantile(0.75)
    IQR = Q3 - Q1
    lim_inf = Q1 - 1.5 * IQR
    lim_sup = Q3 + 1.5 * IQR
    outliers = df[(df[columna] < lim_inf) | (df[columna] > lim_sup)]
    print(f'{columna}:')
    print(f'  Rango normal: [{lim_inf:.2f}, {lim_sup:.2f}]')
    print(f'  Outliers: {len(outliers)} ({len(outliers)/len(df)*100:.1f}%)\n')

# 1. Filtramos para agarrar solo las columnas que tienen números (ignoramos textos/nombres)
columnas_numericas = df_raw.select_dtypes(include=['number']).columns

# 2. Hacemos que Python pase la función por cada una de esas columnas automáticamente
for col in columnas_numericas:
    detectar_outliers(df_raw, col)
    print("-" * 40) # Imprime una línea separadora para que se lea mejor

#:
  Rango normal: [-18.50, 49.50]
  Outliers: 1 (3.4%)

----------------------------------------
Min:
  Rango normal: [-22.50, 157.50]
  Outliers: 0 (0.0%)

----------------------------------------
Gls:
  Rango normal: [0.00, 0.00]
  Outliers: 1 (3.4%)

----------------------------------------
Ast:
  Rango normal: [0.00, 0.00]
  Outliers: 1 (3.4%)

----------------------------------------
PK:
  Rango normal: [0.00, 0.00]
  Outliers: 0 (0.0%)

----------------------------------------
PKatt:
  Rango normal: [0.00, 0.00]
  Outliers: 0 (0.0%)

----------------------------------------
Sh:
  Rango normal: [-1.50, 2.50]
  Outliers: 4 (13.8%)

----------------------------------------
SoT:
  Rango normal: [0.00, 0.00]
  Outliers: 5 (17.2%)

----------------------------------------
CrdY:
  Rango normal: [0.00, 0.00]
  Outliers: 6 (20.7%)

----------------------------------------
CrdR:
  Rango normal: [0.00, 0.00]
  Outliers: 1 (3.4%)

----------------------------------------
Fls:
  Rango normal: [-3.00, 5.00]
  Outliers: 0 (0.0%)

----------------------------------------
Fld:
  Rango normal: [-3.00, 5.00]
  Outliers: 0 (0.0%)

----------------------------------------
Off:
  Rango normal: [0.00, 0.00]
  Outliers: 2 (6.9%)

----------------------------------------
Crs:
  Rango normal: [-1.50, 2.50]
  Outliers: 5 (17.2%)

----------------------------------------
TklW:
  Rango normal: [-3.00, 5.00]
  Outliers: 0 (0.0%)

----------------------------------------
Int:
  Rango normal: [0.00, 0.00]
  Outliers: 7 (24.1%)

----------------------------------------
OG:
  Rango normal: [0.00, 0.00]
  Outliers: 0 (0.0%)

----------------------------------------
edad_dias:
  Rango normal: [-116.00, 420.00]
  Outliers: 0 (0.0%)

----------------------------------------

In [15]:
# Tipos de datos finales
print(df_raw.dtypes)

Player         object
#               int64
Nation         object
Pos            object
Min             int64
Gls             int64
Ast             int64
PK              int64
PKatt           int64
Sh              int64
SoT             int64
CrdY            int64
CrdR            int64
Fls             int64
Fld             int64
Off             int64
Crs             int64
TklW            int64
Int             int64
OG              int64
edad_anios     object
edad_dias     float64
dtype: object

In [18]:
# Convierto el tipo de dato edad_dias a int64
df_raw['edad_dias'] = df_raw['edad_dias'].astype(int)

In [ ]:
# Creamos la columna principal agarrando solo las dos primeras letras de la original
df_raw['Pos_Principal'] = df_raw['Pos'].str[:2]

In [22]:
# ── Recorrer TODAS las columnas de texto (no adivinar a mano) ────────────
columnas_texto = df_raw.select_dtypes(include='object').columns

for col in columnas_texto:
    resultado = detectar_encoding_roto(df_raw, col)
    if len(resultado) > 0:
        print(f'⚠️  {col}: {len(resultado)} valores sospechosos')
        display(resultado[[col]].drop_duplicates())

In [40]:
# ── Diccionarios de traducción FBref ─────────────────────────────────────
# Reutilizable en cualquier análisis de FBref
# Fuente: glosario oficial FBref

COLUMNAS_ES = {
    'Player':     'Jugador',
    '#':          'Camiseta',
    'Pos':        'Posición',
    'Age':        'Edad',
    'Min':        'Minutos',
    'Gls':        'Goles',
    'Ast':        'Asistencias',
    'PK':         'Penales convertidos',
    'PKatt':      'Penales intentados',
    'Sh':         'Tiros totales',
    'SoT':        'Tiros al arco',
    'CrdY':       'Tarjetas amarillas',
    'CrdR':       'Tarjetas rojas',
    'Fls':        'Faltas cometidas',
    'Fld':        'Faltas recibidas',
    'Off':        'Fueras de juego',
    'Crs':        'Centros',
    'TklW':       'Entradas ganadas',
    'Int':        'Intercepciones',
    'OG':         'Goles en contra',
    'PKwon':      'Penales ganados',
    'PKcon':      'Penales concedidos',
    'Edad en años': 'Edad (años)',
    'Edad en días':  'Edad (días de año en curso)'
}

POSICIONES_ES = {
    'GK':   'Arquero',
    'DF':   'Defensor',
    'MF':   'Mediocampista',
    'FW':   'Delantero',
    'FB':   'Lateral',
    'LB':   'Lateral izquierdo',
    'RB':   'Lateral derecho',
    'CB':   'Defensor central',
    'DM':   'Mediocampista defensivo',
    'CM':   'Mediocampista central',
    'LM':   'Mediocampista izquierdo',
    'RM':   'Mediocampista derecho',
    'WM':   'Mediocampista amplio',
    'LW':   'Extremo izquierdo',
    'RW':   'Extremo derecho',
    'AM':   'Mediocampista ofensivo',
    'FWMF': 'Delantero/Mediocampista',
    'MFFW': 'Mediocampista/Delantero',
    'DFMF': 'Defensor/Mediocampista',
    'MFDF': 'Mediocampista/Defensor'
}


def traducir_columnas(df):
    """
    Renombra las columnas de un DataFrame de FBref al español.
    Solo traduce las columnas que existen — no falla si faltan columnas.
    """
    columnas_presentes = {k: v for k, v in COLUMNAS_ES.items() if k in df.columns}
    df = df.rename(columns=columnas_presentes)
    print(f"Columnas traducidas: {len(columnas_presentes)}")
    return df


def traducir_posiciones(df, columna='Posición'):
    """
    Traduce las abreviaturas de posición al español.
    Maneja posiciones combinadas como 'DF,FW' o 'FW,MF'.

    Parámetros:
        columna : nombre de la columna de posición (después de traducir columnas)
    """
    if columna not in df.columns:
        print(f"Columna '{columna}' no encontrada — verificá que ya tradujiste las columnas")
        return df

    def traducir_pos(valor):
        if pd.isna(valor):
            return valor
        # Manejar posiciones combinadas (ej: 'DF,FW', 'FW,MF')
        partes = str(valor).split(',')
        traducidas = [POSICIONES_ES.get(p.strip(), p.strip()) for p in partes]
        return ' / '.join(traducidas)

    df[columna] = df[columna].apply(traducir_pos)
    return df


#── Uso ───────────────────────────────────────────────────────────────────
df_clean = traducir_columnas(df_clean)
df_clean = traducir_posiciones(df_clean)
display(df_clean.head())

Columnas traducidas: 0

,Jugador,Camiseta,Nation,Posición,Minutos,Goles,Asistencias,Penales convertidos,Penales intentados,Tiros totales,Tiros al arco,Tarjetas amarillas,Tarjetas rojas,Faltas cometidas,Faltas recibidas,Fueras de juego,Centros,Entradas ganadas,Intercepciones,Goles en contra,Edad (años),Edad (días de año en curso)
0,Rodrigo Auzmendi,29,ARG,Delantero,90,0,0,0,0,5,1,1,0,2,2,2,0,0,0,0,25,219
1,Alexis Cuello,9,ARG,Delantero,90,0,0,0,0,1,0,0,0,1,3,0,2,1,0,0,26,172
2,Nicolás Tripichio,24,ARG,Mediocampista central,90,0,0,0,0,1,0,0,0,3,2,0,1,1,2,0,30,216
3,Martín Río,27,ARG,Mediocampista central,52,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,25,148
4,Juan Rattalino,13,ARG,Mediocampista,38,0,0,0,0,0,0,0,0,0,1,0,3,0,0,0,22,198

In [44]:
# Le decimos a Pandas: "Buscá a la fila donde el Player sea 'Óscar Romero',
# y en su columna 'Pos_Principal', forzá el valor a 'MF'"
df_clean.loc[df_clean['Posición'] == 'Óscar Romero', 'Pos_Principal'] = 'MF'

KeyError: 'Player'

In [24]:
# Ver si el índice tiene huecos
print(f'Índice antes del reset: {df_raw.index.tolist()[:10]}...')

# Resetear
df_raw = df_raw.reset_index(drop=True)

# Verificar
print(f'Índice después del reset: {df_raw.index.tolist()[:10]}...')
print(f'Filas finales: {df_raw.shape[0]}')

Índice antes del reset: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]...
Índice después del reset: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]...
Filas finales: 29

In [23]:
print('=' * 50)
print('REPORTE FINAL DE CALIDAD')
print('=' * 50)
print(f'Filas finales:      {df_raw.shape[0]}')
print(f'Columnas:           {df_raw.shape[1]}')
print(f'Duplicados:         {df_raw.duplicated().sum()}')
print(f'Nulos totales:      {df_raw.isnull().sum().sum()}')
print('=' * 50)

==================================================
REPORTE FINAL DE CALIDAD
==================================================
Filas finales:      29
Columnas:           22
Duplicados:         0
Nulos totales:      0
==================================================

In [28]:
# Vista previa del dataset limpio
df_raw.head(10)

,Player,#,Nation,Pos,Min,Gls,Ast,PK,PKatt,Sh,SoT,CrdY,CrdR,Fls,Fld,Off,Crs,TklW,Int,OG,edad_anios,edad_dias
0,Rodrigo Auzmendi,29,ARG,FW,90,0,0,0,0,5,1,1,0,2,2,2,0,0,0,0,25,219
1,Alexis Cuello,9,ARG,FW,90,0,0,0,0,1,0,0,0,1,3,0,2,1,0,0,26,172
2,Nicolás Tripichio,24,ARG,CM,90,0,0,0,0,1,0,0,0,3,2,0,1,1,2,0,30,216
3,Martín Río,27,ARG,CM,52,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,25,148
4,Juan Rattalino,13,ARG,MF,38,0,0,0,0,0,0,0,0,0,1,0,3,0,0,0,22,198
5,Facundo Gulli,10,ARG,CM,52,0,0,0,0,0,0,0,0,0,3,0,4,1,0,0,20,318
6,Gustavo Del Prete,21,ARG,FWMF,38,0,0,0,0,0,0,0,0,0,4,0,1,1,0,0,30,58
7,Mathías De Ritis,6,URU,LB,45,0,0,0,0,0,0,1,0,1,2,0,1,2,1,0,23,190
8,Teo Rodríguez,3,ARG,DF,45,0,0,0,0,1,1,0,0,1,0,0,6,1,0,0,20,301
9,Alejo Córdoba,35,ARG,CB,90,0,0,0,0,0,0,0,0,0,1,0,1,3,5,0,22,94

In [27]:
# Renombrar a df_clean antes de exportar
df_clean = df_raw.copy()

# Exportar
nombre_salida = 'san_lorenzo_huracan_clean.csv'
df_clean.to_csv(nombre_salida, index=False, encoding='utf-8')
print(f'Dataset exportado: {nombre_salida}')
print(f'Filas: {df_clean.shape[0]} | Columnas: {df_clean.shape[1]}')

Dataset exportado: san_lorenzo_huracan_clean.csv
Filas: 29 | Columnas: 22

# EDA