In [13]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# ─── Supresión de warnings ─────────────────────────────────────────────────
# import warnings
# warnings.filterwarnings('ignore')          # suprime todos los warnings
# pd.options.mode.chained_assignment = None  # suprime SettingWithCopyWarning

# ─── Configuración de visualización ────────────────────────────────────────
pd.set_option('display.max_columns', None)   # muestra todas las columnas
pd.set_option('display.max_rows', 100)       # muestra hasta 100 filas
pd.set_option('display.float_format', '{:.2f}'.format)  # 2 decimales
plt.style.use('seaborn-v0_8')               # estilo de gráficos profesional
sns.set_palette('husl')

In [14]:
# ── Configuración ──────────────────────────────────────────
DATA_PATH = r"data/tabla_general_semestre_1_2026.csv"  # ← CAMBIAR: ruta al archivo
SEPARATOR = ","                  # ← CAMBIAR si es otro separador (";", "\t", etc.)
ENCODING  = "utf-8"              # ← CAMBIAR si hay problemas de caracteres
# ───────────────────────────────────────────────────────────

df_raw = pd.read_csv(DATA_PATH, sep=SEPARATOR, encoding=ENCODING)
print(f"✅ Dataset cargado — Filas: {df_raw.shape[0]} | Columnas: {df_raw.shape[1]}")

✅ Dataset cargado — Filas: 30 | Columnas: 16

In [15]:
# ─── Primeras y últimas filas ──────────────────────────────────────────────
print('\n--- Primeras 5 filas ---')
display(df_raw.head())

print('\n--- Últimas 5 filas ---')
display(df_raw.tail())

# ─── Dimensiones ───────────────────────────────────────────────────────────
print(f'Filas: {df_raw.shape[0]} | Columnas: {df_raw.shape[1]}')

# ─── Tipos de datos ────────────────────────────────────────────────────────
print('\n--- Info general ---')
df_raw.info()

# ─── Valores nulos por columna ─────────────────────────────────────────────
print('\n--- Nulos por columna ---')
# Verificamos si hay algún nulo en toda la tabla
if df_raw.isnull().sum().sum() == 0:
    print('✅ Sin valores nulos')
else:
    # Sino mostramos tabla filtrada de nulos
    nulos = pd.DataFrame({
        'Nulos': df_raw.isnull().sum(),
        'Porcentaje': (df_raw.isnull().sum() / len(df_raw) * 100).round(2)
    })
    display(nulos[nulos['Nulos'] > 0])

# ─── Duplicados ────────────────────────────────────────────────────────────
print(f'\nFilas duplicadas: {df_raw.duplicated().sum()}')

# ─── Estadísticas descriptivas ─────────────────────────────────────────────
print('\n--- Estadísticas descriptivas ---')
display(df_raw.describe())

--- Primeras 5 filas ---

,Rk,Squad,MP,W,D,L,GF,GA,GD,Pts,Pts/MP,Last 5,Attendance,Top Team Scorer,Goalkeeper,Notes
0,1,Club Crest Ind. Rivadavia,16,10,4,2,29,15,14,34,2.13,W D W D L,NaN,Fabrizio Sartori - 6,Nicolás Bolcato,NaN
1,2,Club Crest Estudiantes–LP,16,9,4,3,19,7,12,31,1.94,W W D W L,NaN,"Alexis Castro, Adolfo Gaich... - 3",Fernando Muslera,NaN
2,3,Club Crest Boca Juniors,16,8,6,2,22,9,13,30,1.88,D W W W L,NaN,Miguel Merentiel - 5,Agustín Marchesín,NaN
3,4,Club Crest River Plate,16,9,2,5,22,12,10,29,1.81,L D W W L,NaN,"Sebastián Driussi, Gonzalo Montiel - 4",Santiago Beltrán,NaN
4,5,Club Crest Arg Juniors,16,8,5,3,17,13,4,29,1.81,W L W W D,NaN,Tomás Molina - 3,Brayan Cortés,NaN

--- Últimas 5 filas ---

,Rk,Squad,MP,W,D,L,GF,GA,GD,Pts,Pts/MP,Last 5,Attendance,Top Team Scorer,Goalkeeper,Notes
25,26,Club Crest Newell's Old Boys,16,3,6,7,15,27,-12,15,0.94,W D W D D,NaN,Juan Ignacio Ramírez - 4,Gabriel Arias,NaN
26,27,Club Crest Atlé Tucumán,16,3,5,8,15,20,-5,14,0.88,L D L D W,NaN,Leandro Díaz - 5,Luis Ingolotti,NaN
27,28,Club Crest Deportivo Riestra,16,1,8,7,5,12,-7,11,0.69,L L L W D,NaN,Antony Alonso - 2,Ignacio Arce,NaN
28,29,Club Crest Aldosivi,16,0,8,8,6,19,-13,8,0.50,D L D L D,NaN,Federico Gino - 2,Axel Werner,NaN
29,30,Club Crest Estudiantes–RC,16,1,2,13,5,24,-19,5,0.31,D L L L L,NaN,"Gabriel Alanís, Facundo Cobos... - 1",Agustín Lastra,NaN

Filas: 30 | Columnas: 16

--- Info general ---
<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Rk               30 non-null     int64
 1   Squad            30 non-null     str
 2   MP               30 non-null     int64
 3   W                30 non-null     int64
 4   D                30 non-null     int64
 5   L                30 non-null     int64
 6   GF               30 non-null     int64
 7   GA               30 non-null     int64
 8   GD               30 non-null     int64
 9   Pts              30 non-null     int64
 10  Pts/MP           30 non-null     float64
 11  Last 5           30 non-null     str
 12  Attendance       0 non-null      float64
 13  Top Team Scorer  30 non-null     str
 14  Goalkeeper       30 non-null     str
 15  Notes            0 non-null      float64
dtypes: float64(3), int64(9), str(4)
memory usage: 3.9 KB

--- Nulos por columna ---

            Nulos  Porcentaje
Attendance     30      100.00
Notes          30      100.00

Filas duplicadas: 0

--- Estadísticas descriptivas ---

,Rk,MP,W,D,L,GF,GA,GD,Pts,Pts/MP,Attendance,Notes
count,30.00,30.00,30.00,30.00,30.00,30.00,30.00,30.00,30.00,30.00,0.00,0.00
mean,15.50,16.00,5.43,5.13,5.43,16.43,16.43,0.00,21.43,1.34,NaN,NaN
std,8.80,0.00,2.46,1.94,2.43,5.39,4.48,7.83,6.82,0.43,NaN,NaN
min,1.00,16.00,0.00,1.00,2.00,5.00,7.00,-19.00,5.00,0.31,NaN,NaN
25%,8.25,16.00,4.00,4.00,4.00,14.25,13.00,-5.00,18.25,1.15,NaN,NaN
50%,15.50,16.00,5.00,5.50,5.00,17.00,15.00,1.00,21.00,1.31,NaN,NaN
75%,22.75,16.00,7.00,6.75,7.00,18.75,20.00,4.00,26.00,1.63,NaN,NaN
max,30.00,16.00,10.00,8.00,13.00,29.00,27.00,14.00,34.00,2.13,NaN,NaN

In [17]:
df_raw = df_raw.drop(columns=['Attendance', 'Notes'])